DATABASE:
  HOST: "localhost"
  PORT: "5432"
  USER: "postgres"
PORT:
  AUTH: "8080"
  APPOINTMENT: "8081"
  STUDENT: "8082"
  PROJECT: "8083"
  ADMIN:
    APPLICATION: "3492"
MAIL:
  HOST: "smtp.cc.iitk.ac.in"
  PORT: "25"
DBNAME:
  AUTH: "auth"
  STUDENT: "student"
  APPOINTMENT: "appointment"
  PROJECT: "project"
  APPLICATION: "application"
OTP:
  EXPIRATION: 20
  SIZE: 6

   