DATABASE:
  HOST: "localhost"
  PORT: "5432"
  USER: "postgres"
PORT:
  AUTH: "8084"
  STUDENT: "8082"
  PROJECT: "8083"
  PROF: "8081"
  ADMIN:
    APPLICATION: "3492"
    PROF: "3490"
    STUDENT: 3500

MAIL:
  HOST: "mmtp.iitk.ac.in"
  PORT: "25"
DBNAME:
  PROF: "prof"
  AUTH: "auth"
  STUDENT: "student"
  APPOINTMENT: "appointment"
  PROJECT: "project"
  APPLICATION: "application"
OTP:
  EXPIRATION: 20
  SIZE: 6
JWT:
  EXPIRATION:
    LONG: 5000
    SHORT: 200
   